server:
  port: 8080

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      routes:

        - id: ms-auth
          uri: http://ms-auth:8080
          predicates:
            - Path=/auth/**

        - id: demo
          uri: http://demo:8080
          predicates:
            - Path=/api/v1/**

        - id: ms-pedidos
          uri: http://ms-pedidos:8080
          predicates:
            - Path=/pedidos/**, /productos/**
 

jwt:
  secret: myVerySecretKeyForJwtAuthentication123456789
  expiration: 3600000